on:
  push:
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:
    inputs:
      VERSION:
        description: version
        required: true
        default: "RELEASE.2022-10-24T18-35-07Z"

name: ci

env:
  MINIO_CUSTOM_VERSION: ${{ github.event.inputs.VERSION }}

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PLATFORM: ["windows-amd64","darwin-arm64","darwin-amd64"]
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PLATFORM: windows-amd64
    steps:
    - env: 
        PLATFORM: ${{ matrix.PLATFORM }}
        CODING_USERNAME: khs1994-1601432822176
        CODING_TOKEN: ${{secrets.CODING_DOCKER_PASSWORD}}
        CODING_URL: https://pcit-generic.pkg.coding.net/khs1994-docker/kubernetes
      run: |
        set -x
        
        mkdir minio ; cd minio

        MINIO_FILE_NAME="minio"
        MC_FILE_NAME="mc"

        if [ $PLATFORM = 'windows-amd64' ];then
          MINIO_FILE_NAME="minio.exe"
          MC_FILE_NAME="mc.exe"
        fi

        if [ -n "${MINIO_CUSTOM_VERSION}" ];then
          curl https://dl.min.io/server/minio/release/${PLATFORM}/archive/minio.${MINIO_CUSTOM_VERSION} -o minio.${MINIO_CUSTOM_VERSION}.${PLATFORM}.zip
          gh release upload nightly minio.${MINIO_CUSTOM_VERSION}.${PLATFORM}.zip -R khs1994-docker/minio-mirror --clobber
          curl -T "minio.${MINIO_CUSTOM_VERSION}.${PLATFORM}.zip" -u ${CODING_USERNAME}:${CODING_TOKEN} \
            "${CODING_URL}/${ZIP_FILE}?version=latest"
        fi

        export ZIP_FILE="minio-${PLATFORM}.zip"
        zip ${ZIP_FILE} $MINIO_FILE_NAME $MC_FILE_NAME
        gh release upload nightly "${ZIP_FILE}" -R khs1994-docker/minio-mirror --clobber


        curl -T "${ZIP_FILE}" -u ${CODING_USERNAME}:${CODING_TOKEN} \
          "${CODING_URL}/${ZIP_FILE}?version=latest"
