on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 4'

name: ci

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PLATFORM: ["windows-amd64","darwin-arm64","darwin-amd64"]
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      PLATFORM: windows-amd64
    steps:
    - env: 
        PLATFORM: ${{ matrix.PLATFORM }}
      run: |
        mkdir minio ; cd minio

        $MINIO_FILE_NAME="minio"
        $MC_FILE_NAME="mc"

        if [ $PLATFORM = 'windows-amd64' ];then
          $MINIO_FILE_NAME="minio.exe"
          $MC_FILE_NAME="mc.exe"
        fi

        curl -O https://dl.min.io/server/minio/release/${PLATFORM}/$MINIO_FILE_NAME
        curl -O https://dl.min.io/client/mc/release/${PLATFORM}/$MC_FILE_NAME

        export ZIP_FILE="minio-${PLATFORM}.zip"
        zip ${ZIP_FILE} minio.exe mc.exe
        gh release upload nightly "${ZIP_FILE}" -R khs1994-docker/minio-mirror --clobber
